# Generated by Django 5.0.1 on 2025-11-08 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RADIOGRAFIA', 'Radiografía'), ('ECOGRAFIA', 'Ecografía'), ('LABORATORIO', 'Análisis de Laboratorio'), ('FOTO', 'Fotografía'), ('DOCUMENTO', 'Documento'), ('OTRO', 'Otro')], default='DOCUMENTO', max_length=20, verbose_name='Tipo de Adjunto')),
                ('archivo', models.FileField(upload_to='hce/adjuntos/%Y/%m/', verbose_name='Archivo')),
                ('titulo', models.CharField(help_text='Título descriptivo del archivo', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='ConstantesVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en kilogramos', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Peso (kg)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, help_text='Temperatura corporal en grados Celsius', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(45.0)], verbose_name='Temperatura (°C)')),
                ('frecuencia_cardiaca', models.PositiveIntegerField(blank=True, help_text='Latidos por minuto', null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(300)], verbose_name='Frecuencia Cardíaca (lpm)')),
                ('frecuencia_respiratoria', models.PositiveIntegerField(blank=True, help_text='Respiraciones por minuto', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)], verbose_name='Frecuencia Respiratoria (rpm)')),
                ('presion_arterial_sistolica', models.PositiveIntegerField(blank=True, null=True, verbose_name='Presión Arterial Sistólica (mmHg)')),
                ('presion_arterial_diastolica', models.PositiveIntegerField(blank=True, null=True, verbose_name='Presión Arterial Diastólica (mmHg)')),
                ('tiempo_llenado_capilar', models.DecimalField(blank=True, decimal_places=1, help_text='Tiempo en segundos', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)], verbose_name='Tiempo de Llenado Capilar (seg)')),
                ('condicion_corporal', models.PositiveIntegerField(blank=True, help_text='Escala de 1 a 9 (1: muy delgado, 5: ideal, 9: obeso)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)], verbose_name='Condición Corporal')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre las constantes vitales', verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Constantes Vitales',
                'verbose_name_plural': 'Constantes Vitales',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='EpisodioClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField(help_text='Razón principal por la que se consulta', verbose_name='Motivo de Consulta')),
                ('anamnesis', models.TextField(help_text='Historia clínica y antecedentes relevantes del episodio', verbose_name='Anamnesis')),
                ('examen_fisico', models.TextField(help_text='Hallazgos del examen físico general', verbose_name='Examen Físico')),
                ('diagnostico_presuntivo', models.TextField(help_text='Diagnóstico inicial basado en examen clínico', verbose_name='Diagnóstico Presuntivo')),
                ('diagnostico_definitivo', models.TextField(blank=True, help_text='Diagnóstico confirmado con pruebas complementarias', verbose_name='Diagnóstico Definitivo')),
                ('plan_tratamiento', models.TextField(help_text='Descripción del tratamiento prescrito', verbose_name='Plan de Tratamiento')),
                ('medicamentos', models.TextField(blank=True, help_text='Lista de medicamentos con dosis y duración', verbose_name='Medicamentos Prescritos')),
                ('procedimientos', models.TextField(blank=True, help_text='Descripción de procedimientos o intervenciones realizadas', verbose_name='Procedimientos Realizados')),
                ('pronostico', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('RESERVADO', 'Reservado'), ('GRAVE', 'Grave')], default='BUENO', max_length=20, verbose_name='Pronóstico')),
                ('indicaciones', models.TextField(blank=True, help_text='Instrucciones para el cuidado en casa', verbose_name='Indicaciones al Tutor')),
                ('proxima_revision', models.DateField(blank=True, help_text='Fecha recomendada para próxima consulta', null=True, verbose_name='Próxima Revisión')),
                ('episodio_cerrado', models.BooleanField(default=False, help_text='Indica si el episodio clínico fue finalizado', verbose_name='Episodio Cerrado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Episodio Clínico',
                'verbose_name_plural': 'Episodios Clínicos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
