# Generated by Django 5.0.1 on 2025-11-08 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_initial'),
        ('hce', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adjunto',
            name='subido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddField(
            model_name='constantesvitales',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='episodioclinico',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='episodio_clinico', to='citas.cita', verbose_name='Cita Asociada'),
        ),
        migrations.AddField(
            model_name='episodioclinico',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodios_clinicos', to='pacientes.mascota', verbose_name='Mascota'),
        ),
        migrations.AddField(
            model_name='episodioclinico',
            name='medico',
            field=models.ForeignKey(limit_choices_to={'rol': 'MEDICO'}, on_delete=django.db.models.deletion.PROTECT, related_name='episodios_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Médico Tratante'),
        ),
        migrations.AddField(
            model_name='constantesvitales',
            name='episodio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantes_vitales', to='hce.episodioclinico', verbose_name='Episodio Clínico'),
        ),
        migrations.AddField(
            model_name='adjunto',
            name='episodio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='hce.episodioclinico', verbose_name='Episodio Clínico'),
        ),
        migrations.AddIndex(
            model_name='episodioclinico',
            index=models.Index(fields=['mascota', '-fecha_creacion'], name='hce_episodi_mascota_540960_idx'),
        ),
        migrations.AddIndex(
            model_name='episodioclinico',
            index=models.Index(fields=['medico', '-fecha_creacion'], name='hce_episodi_medico__db7941_idx'),
        ),
        migrations.AddIndex(
            model_name='episodioclinico',
            index=models.Index(fields=['cita'], name='hce_episodi_cita_id_41e33e_idx'),
        ),
    ]
