# Generated by Django 5.0.1 on 2025-11-08 20:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=100, verbose_name='Número de Lote')),
                ('fecha_fabricacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Fabricación')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('stock_inicial', models.PositiveIntegerField(help_text='Cantidad inicial del lote', verbose_name='Stock Inicial')),
                ('stock_actual', models.PositiveIntegerField(verbose_name='Stock Actual')),
                ('precio_compra_lote', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Compra del Lote')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único identificador del producto', max_length=50, unique=True, verbose_name='Código del Producto')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('VACUNA', 'Vacuna'), ('SUMINISTRO_MEDICO', 'Suministro Médico'), ('ALIMENTO', 'Alimento'), ('HIGIENE', 'Higiene'), ('ACCESORIO', 'Accesorio'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Categoría')),
                ('principio_activo', models.CharField(blank=True, help_text='Componente activo principal (para medicamentos)', max_length=200, verbose_name='Principio Activo')),
                ('concentracion', models.CharField(blank=True, help_text='Ej: 500mg, 10ml', max_length=100, verbose_name='Concentración')),
                ('laboratorio', models.CharField(blank=True, max_length=200, verbose_name='Laboratorio/Fabricante')),
                ('unidad_medida', models.CharField(choices=[('UNIDAD', 'Unidad'), ('CAJA', 'Caja'), ('FRASCO', 'Frasco'), ('AMPOLLA', 'Ampolla'), ('TABLETA', 'Tableta'), ('CAPSULA', 'Cápsula'), ('ML', 'Mililitros'), ('GR', 'Gramos'), ('KG', 'Kilogramos')], default='UNIDAD', max_length=15, verbose_name='Unidad de Medida')),
                ('stock_minimo', models.PositiveIntegerField(default=10, help_text='Cantidad mínima antes de generar alerta', verbose_name='Stock Mínimo')),
                ('stock_maximo', models.PositiveIntegerField(default=100, help_text='Cantidad máxima recomendada', verbose_name='Stock Máximo')),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Compra')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta')),
                ('requiere_receta', models.BooleanField(default=False, verbose_name='Requiere Receta Médica')),
                ('control_lote', models.BooleanField(default=True, help_text='Indica si el producto se controla por lotes y fechas de vencimiento', verbose_name='Control por Lote')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Donación)'), ('SALIDA_VENTA', 'Salida por Venta'), ('SALIDA_USO', 'Salida por Uso Clínico'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('MERMA', 'Merma/Vencimiento'), ('DEVOLUCION', 'Devolución')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(help_text='Cantidad del movimiento (positivo o negativo)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('stock_anterior', models.PositiveIntegerField(verbose_name='Stock Anterior')),
                ('stock_nuevo', models.PositiveIntegerField(verbose_name='Stock Nuevo')),
                ('motivo', models.TextField(help_text='Descripción del motivo del movimiento', verbose_name='Motivo/Observaciones')),
                ('documento_referencia', models.CharField(blank=True, help_text='Ej: Número de factura, orden de compra, etc.', max_length=100, verbose_name='Documento de Referencia')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('episodio_clinico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='hce.episodioclinico', verbose_name='Episodio Clínico')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
