# Generated by Django 5.0.1 on 2025-11-08 20:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Especie')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Raza')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
                'ordering': ['especie', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra'), ('D', 'Desconocido')], default='D', max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Color/Patrón')),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Peso Actual (kg)')),
                ('microchip', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Microchip')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pacientes/fotos/', verbose_name='Foto de la Mascota')),
                ('esterilizado', models.BooleanField(default=False, verbose_name='Esterilizado/Castrado')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias Conocidas')),
                ('condiciones_cronicas', models.TextField(blank=True, verbose_name='Condiciones Crónicas')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Generales')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la mascota está activa en el sistema', verbose_name='Activo')),
                ('fallecido', models.BooleanField(default=False, verbose_name='Fallecido')),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Fallecimiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to='pacientes.especie', verbose_name='Especie')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
