# Generated by Django 5.0.1 on 2025-11-08 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'rol': 'TUTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='mascotas', to=settings.AUTH_USER_MODEL, verbose_name='Tutor'),
        ),
        migrations.AddField(
            model_name='raza',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razas', to='pacientes.especie', verbose_name='Especie'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mascotas', to='pacientes.raza', verbose_name='Raza'),
        ),
        migrations.AlterUniqueTogether(
            name='raza',
            unique_together={('especie', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='mascota',
            index=models.Index(fields=['tutor', 'activo'], name='pacientes_m_tutor_i_92a3be_idx'),
        ),
        migrations.AddIndex(
            model_name='mascota',
            index=models.Index(fields=['especie'], name='pacientes_m_especie_b8f02e_idx'),
        ),
        migrations.AddIndex(
            model_name='mascota',
            index=models.Index(fields=['microchip'], name='pacientes_m_microch_3554d7_idx'),
        ),
    ]
