# Generated by Django 5.0.1 on 2025-11-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora de la Cita')),
                ('duracion_estimada', models.PositiveIntegerField(default=30, help_text='Duración estimada de la cita en minutos', verbose_name='Duración Estimada (minutos)')),
                ('tipo_cita', models.CharField(choices=[('CONSULTA_GENERAL', 'Consulta General'), ('VACUNACION', 'Vacunación'), ('CIRUGIA', 'Cirugía'), ('EMERGENCIA', 'Emergencia'), ('CONTROL', 'Control'), ('DESPARASITACION', 'Desparasitación'), ('OTRO', 'Otro')], default='CONSULTA_GENERAL', max_length=30, verbose_name='Tipo de Cita')),
                ('estado', models.CharField(choices=[('RESERVADA', 'Reservada'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En Curso'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No Asistió')], default='RESERVADA', max_length=15, verbose_name='Estado')),
                ('motivo', models.TextField(help_text='Descripción breve del motivo de la cita', verbose_name='Motivo de la Consulta')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales para la cita', verbose_name='Observaciones')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas visibles solo para el personal', verbose_name='Notas Internas')),
                ('recordatorio_enviado', models.BooleanField(default=False, verbose_name='Recordatorio Enviado')),
                ('fecha_recordatorio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recordatorio')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Atención')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación')),
                ('motivo_cancelacion', models.TextField(blank=True, verbose_name='Motivo de Cancelación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora'],
            },
        ),
    ]
