# Generated by Django 5.0.1 on 2025-11-08 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='pacientes.mascota', verbose_name='Mascota'),
        ),
        migrations.AddField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'MEDICO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='citas_como_medico', to=settings.AUTH_USER_MODEL, verbose_name='Médico Veterinario'),
        ),
        migrations.AddField(
            model_name='cita',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'rol': 'TUTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='citas_como_tutor', to=settings.AUTH_USER_MODEL, verbose_name='Tutor'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_hora', 'estado'], name='citas_cita_fecha_h_e91b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['mascota', 'estado'], name='citas_cita_mascota_fa71cb_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['medico', 'fecha_hora'], name='citas_cita_medico__fa0c00_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['tutor', 'fecha_hora'], name='citas_cita_tutor_i_bcd41a_idx'),
        ),
    ]
